name: Test and Merge to Production

on:
  pull_request:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.11.0'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git user
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Merge to Production
      run: |
        git checkout production
        git merge master --no-ff --commit-message "Merge successful tests from master"
        git push origin production
