name: Test and Deploy to Production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.11.0'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git user
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Push changes to production
      run: |
        git fetch origin
        git checkout production
        git merge master --no-ff --allow-unrelated-histories -m "Sync master with production"
        git push origin production
